INSERT INTO bevanda (idbevanda, nome, photo_url, livello_alcolico, descrizione, categoria, prezzo) VALUES (1, 'Birra Moretti', 'https://www.example.com/birra-moretti.jpg', 5.1, 'Birra bionda italiana di qualità', 'drinkalcolici', 2.5);
INSERT INTO bevanda (idbevanda, nome, photo_url, livello_alcolico, descrizione, categoria, prezzo) VALUES (2, 'Coca Cola', 'https://www.example.com/coca-cola.jpg', 0, 'Bevanda analcolica al gusto di cola', 'drinkanalcolici', 1.5);
INSERT INTO bevanda (idbevanda, nome, photo_url, livello_alcolico, descrizione, categoria, prezzo) VALUES (3, 'Vodka Smirnoff', 'https://www.example.com/vodka-smirnoff.jpg', 40, 'Vodka di alta qualità', 'softdrink', 3.5);
INSERT INTO bevanda (idbevanda, nome, photo_url, livello_alcolico, descrizione, categoria, prezzo) VALUES (4, 'Red Bull', 'https://www.example.com/red-bull.jpg', 0, 'Bevanda energetica', 'drinkanalcolici', 2.5);
INSERT INTO bevanda (idbevanda, nome, photo_url, livello_alcolico, descrizione, categoria, prezzo) VALUES (5, 'Coca Cola Zero', 'https://www.example.com/coca-cola-zero.jpg', 0, 'Bevanda analcolica al gusto di cola senza zucchero', 'drinkanalcolici', 1.5);
INSERT INTO bevanda (idbevanda, nome, photo_url, livello_alcolico, descrizione, categoria, prezzo) VALUES (6, 'Acqua Minerale', 'https://www.example.com/acqua-minerale.jpg', 0, 'Acqua naturale italiana', 'drinkanalcolici', 1);
INSERT INTO bevanda (idbevanda, nome, photo_url, livello_alcolico, descrizione, categoria, prezzo) VALUES (7, 'Birra Guinness', 'https://www.example.com/birra-guinness.jpg', 4.2, 'Birra scura irlandese di qualità', 'drinkalcolici', 4);
INSERT INTO bevanda (idbevanda, nome, photo_url, livello_alcolico, descrizione, categoria, prezzo) VALUES (8, 'Tequila Jose Cuervo', 'https://www.example.com/tequila-jose-cuervo.jpg', 38, 'Tequila di alta qualità', 'drinkalcolici', 4.5);
INSERT INTO bevanda (idbevanda, nome, photo_url, livello_alcolico, descrizione, categoria, prezzo) VALUES (9, 'Fanta', 'https://www.example.com/fanta.jpg', 0, 'Bevanda analcolica all''arancia', 'drinkanalcolici', 1.5);
